/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Tahoma16b.c                                           *
* Font:        Tahoma                                                *
* Height:      16                                                    *
* Type:        standart                                              *
* Encoding:    8 bit ASCII + ISO 8859                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
GUI_CONST_STORAGE GUI_FONT GUI_FontTahoma16b;

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0020[ 16] = { /* code 0020 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0021[ 16] = { /* code 0021 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0022[ 16] = { /* code 0022 */
  ________,
  ________,
  ________,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0023[ 32] = { /* code 0023 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X__X_,________,
  ___X__X_,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  __X__X__,________,
  XXXXXXX_,________,
  XXXXXXX_,________,
  _X__X___,________,
  _X__X___,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0024[ 16] = { /* code 0024 */
  ________,
  ________,
  ___X____,
  ___X____,
  _XXXXX__,
  XX_X__X_,
  XX_X____,
  XX_X____,
  _XXXXX__,
  ___X_XX_,
  ___X_XX_,
  X__X_XX_,
  _XXXXX__,
  ___X____,
  ___X____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0025[ 32] = { /* code 0025 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXX___,________,
  XX__XX__,_X______,
  XX__XX__,X_______,
  XX__XX_X,________,
  _XXXX_X_,XXXX____,
  _____X_X,X__XX___,
  ____X__X,X__XX___,
  ___X___X,X__XX___,
  ________,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0026[ 32] = { /* code 0026 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXX__,________,
  _XX__XX_,________,
  _XX__XX_,________,
  _XX__XX_,________,
  __XXXX__,XX______,
  _XX__XX_,XX______,
  _XX___XX,X_______,
  _XX___XX,________,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0027[ 16] = { /* code 0027 */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0028[ 16] = { /* code 0028 */
  ________,
  ________,
  ________,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0029[ 16] = { /* code 0029 */
  ________,
  ________,
  ________,
  _XX_____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_002A[ 16] = { /* code 002A */
  ________,
  ________,
  ________,
  ___XX___,
  _X_XX_X_,
  __XXXX__,
  _X_XX_X_,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_002B[ 32] = { /* code 002B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  __XXXXXX,X_______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_002C[ 16] = { /* code 002C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  XX______,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_002D[ 16] = { /* code 002D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_002E[ 16] = { /* code 002E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_002F[ 16] = { /* code 002F */
  ________,
  ________,
  ________,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0030[ 16] = { /* code 0030 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0031[ 16] = { /* code 0031 */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0032[ 16] = { /* code 0032 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  X____XX_,
  X____XX_,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XXXXXXX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0033[ 16] = { /* code 0033 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  X____XX_,
  _____XX_,
  _____XX_,
  __XXXX__,
  _____XX_,
  _____XX_,
  X____XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0034[ 16] = { /* code 0034 */
  ________,
  ________,
  ________,
  ________,
  ____XX__,
  ___XXX__,
  __X_XX__,
  _X__XX__,
  X___XX__,
  XXXXXXX_,
  ____XX__,
  ____XX__,
  ____XX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0035[ 16] = { /* code 0035 */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _XX_____,
  _XX_____,
  _XXXXX__,
  _____XX_,
  _____XX_,
  _____XX_,
  X____XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0036[ 16] = { /* code 0036 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX_____,
  XX______,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0037[ 16] = { /* code 0037 */
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _____XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0038[ 16] = { /* code 0038 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0039[ 16] = { /* code 0039 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXXX_,
  _____XX_,
  ____XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_003A[ 16] = { /* code 003A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_003B[ 16] = { /* code 003B */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  XX______,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_003C[ 32] = { /* code 003C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  _____XX_,________,
  ___XX___,________,
  _XX_____,________,
  _XX_____,________,
  ___XX___,________,
  _____XX_,________,
  _______X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_003D[ 32] = { /* code 003D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_003E[ 32] = { /* code 003E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,________,
  ___XX___,________,
  _____XX_,________,
  _______X,X_______,
  _______X,X_______,
  _____XX_,________,
  ___XX___,________,
  _XX_____,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_003F[ 16] = { /* code 003F */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  X___XX__,
  ____XX__,
  ___XX___,
  __XX____,
  __XX____,
  ________,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0040[ 32] = { /* code 0040 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXX_,________,
  _X_____X,________,
  X__XXXX_,X_______,
  X_XX_XX_,X_______,
  X_XX_XX_,X_______,
  X_XX_XX_,X_______,
  X_XX_XX_,X_______,
  X__XX_XX,________,
  _X______,________,
  __XXXXXX,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0041[ 32] = { /* code 0041 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  __XX_XX_,________,
  __XX_XX_,________,
  _XX___XX,________,
  _XXXXXXX,________,
  _XX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0042[ 16] = { /* code 0042 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0043[ 16] = { /* code 0043 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX____X_,
  XX____X_,
  XX______,
  XX______,
  XX______,
  XX____X_,
  XX____X_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0044[ 32] = { /* code 0044 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXX__,________,
  XX___XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XX_,________,
  XXXXXX__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0045[ 16] = { /* code 0045 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0046[ 16] = { /* code 0046 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0047[ 16] = { /* code 0047 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX____X_,
  XX____X_,
  XX______,
  XX__XXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0048[ 32] = { /* code 0048 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XXXXXXXX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0049[ 16] = { /* code 0049 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_004A[ 16] = { /* code 004A */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_004B[ 16] = { /* code 004B */
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX__XX__,
  XX_XX___,
  XXXX____,
  XXX_____,
  XXXX____,
  XX_XX___,
  XX__XX__,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_004C[ 16] = { /* code 004C */
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_004D[ 32] = { /* code 004D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXX____X,XX______,
  XXX____X,XX______,
  X_XX__X_,XX______,
  X_XX__X_,XX______,
  X__XXX__,XX______,
  X__XXX__,XX______,
  X___X___,XX______,
  X___X___,XX______,
  X_______,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_004E[ 16] = { /* code 004E */
  ________,
  ________,
  ________,
  ________,
  XXX___X_,
  XXX___X_,
  X_XX__X_,
  X_XX__X_,
  X__XX_X_,
  X__XX_X_,
  X___XXX_,
  X___XXX_,
  X____XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_004F[ 32] = { /* code 004F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XXXXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0050[ 16] = { /* code 0050 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0051[ 32] = { /* code 0051 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XXXXXX_,________,
  _____XX_,________,
  ______XX,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0052[ 32] = { /* code 0052 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXX__,________,
  XX___XX_,________,
  XX___XX_,________,
  XX___XX_,________,
  XXXXXX__,________,
  XX_XX___,________,
  XX__XX__,________,
  XX___XX_,________,
  XX____XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0053[ 16] = { /* code 0053 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX____X_,
  XX____X_,
  XX______,
  _XXXXX__,
  _____XX_,
  X____XX_,
  X____XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0054[ 16] = { /* code 0054 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0055[ 16] = { /* code 0055 */
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0056[ 32] = { /* code 0056 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  _XX__XX_,________,
  __XXXX__,________,
  __XXXX__,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0057[ 32] = { /* code 0057 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX__XXXX,__XX____,
  _XX_XXXX,_XX_____,
  _XXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  __XX____,XX______,
  __XX____,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0058[ 32] = { /* code 0058 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  __XXXX__,________,
  ___XX___,________,
  __XXXX__,________,
  _XX__XX_,________,
  XX____XX,________,
  XX____XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0059[ 32] = { /* code 0059 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  _XX__XX_,________,
  __XXXX__,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_005A[ 16] = { /* code 005A */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  ____XX__,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_005B[ 16] = { /* code 005B */
  ________,
  ________,
  ________,
  _XXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXX___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_005C[ 16] = { /* code 005C */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  _____X__,
  _____X__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_005D[ 16] = { /* code 005D */
  ________,
  ________,
  ________,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXXX___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_005E[ 32] = { /* code 005E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  ___X__X_,________,
  __X____X,________,
  _X______,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_005F[ 16] = { /* code 005F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXXX,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0060[ 16] = { /* code 0060 */
  ________,
  ________,
  ________,
  __XX____,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0061[ 16] = { /* code 0061 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  _____XX_,
  _XXXXXX_,
  XX___XX_,
  XX___XX_,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0062[ 16] = { /* code 0062 */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX_XXX__,
  XXX__XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0063[ 16] = { /* code 0063 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX___X__,
  XX______,
  XX______,
  XX______,
  XX___X__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0064[ 16] = { /* code 0064 */
  ________,
  ________,
  ________,
  _____XX_,
  _____XX_,
  _____XX_,
  _XXXXXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX__XXX_,
  _XXX_XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0065[ 16] = { /* code 0065 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XXXXXXX_,
  XX______,
  XX____X_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0066[ 16] = { /* code 0066 */
  ________,
  ________,
  ________,
  __XXX___,
  _XX_____,
  _XX_____,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0067[ 16] = { /* code 0067 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX__XXX_,
  _XXX_XX_,
  _____XX_,
  X____XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0068[ 16] = { /* code 0068 */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX_XXX__,
  XXX__XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0069[ 16] = { /* code 0069 */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_006A[ 16] = { /* code 006A */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_006B[ 16] = { /* code 006B */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX__XX__,
  XX_XX___,
  XXXX____,
  XXX_____,
  XXXX____,
  XX_XX___,
  XX__XX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_006C[ 16] = { /* code 006C */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_006D[ 32] = { /* code 006D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXX_XX,X_______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_006E[ 16] = { /* code 006E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XXX__,
  XXX__XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_006F[ 16] = { /* code 006F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0070[ 16] = { /* code 0070 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XXX__,
  XXX__XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0071[ 16] = { /* code 0071 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX__XXX_,
  _XXX_XX_,
  _____XX_,
  _____XX_,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0072[ 16] = { /* code 0072 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0073[ 16] = { /* code 0073 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX___X__,
  XXX_____,
  _XXXX___,
  ___XXX__,
  X___XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0074[ 16] = { /* code 0074 */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  XXXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0075[ 16] = { /* code 0075 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX__XXX_,
  _XXX_XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0076[ 16] = { /* code 0076 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0077[ 32] = { /* code 0077 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX__XX__,XX______,
  XX__XX__,XX______,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  _XXX__XX,X_______,
  __XX__XX,________,
  __XX__XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0078[ 16] = { /* code 0078 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  __XX____,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_0079[ 16] = { /* code 0079 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  __XXX___,
  ___XX___,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_007A[ 16] = { /* code 007A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_007B[ 16] = { /* code 007B */
  ________,
  ________,
  ________,
  ___XXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXX_____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ___XXX__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_007C[ 16] = { /* code 007C */
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_007D[ 16] = { /* code 007D */
  ________,
  ________,
  ________,
  XXX_____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ___XXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXX_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_007E[ 32] = { /* code 007E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXX___,_X______,
  XXXXXX__,_X______,
  X___XXXX,XX______,
  X____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_007F[ 32] = { /* code 007F */
  ________,________,
  ________,________,
  ________,________,
  XXXX____,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXXX____,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00A0[ 16] = { /* code 00A0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00A1[ 32] = { /* code 00A1 */
  _X____X_,________,
  _X____X_,________,
  __XXXX__,________,
  ________,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  _XX__XX_,________,
  __XXXX__,________,
  ___XXX__,________,
  ___XX___,________,
  ___XX___,________,
  _XXX____,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00A2[ 16] = { /* code 00A2 */
  ________,
  ________,
  ________,
  _X___X__,
  __XXX___,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  __XXX___,
  ___XX___,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00A3[ 16] = { /* code 00A3 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00A4[ 16] = { /* code 00A4 */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_____X_,
  _XXXXX__,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXXX__,
  X_____X_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00A5[ 16] = { /* code 00A5 */
  ________,
  ____XX__,
  ____XX__,
  ____XX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00A6[ 16] = { /* code 00A6 */
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00A7[ 16] = { /* code 00A7 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX____X_,
  XX______,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  _____XX_,
  X____XX_,
  _XXXXX__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00A8[ 16] = { /* code 00A8 */
  ________,
  _XX_XX__,
  _XX_XX__,
  ________,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00A9[ 32] = { /* code 00A9 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __X_____,X_______,
  _X______,_X______,
  X___XXXX,__X_____,
  X__XX___,__X_____,
  X__XX___,__X_____,
  X__XX___,__X_____,
  X___XXXX,__X_____,
  _X______,_X______,
  __X_____,X_______,
  ___XXXXX,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00AA[ 16] = { /* code 00AA */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX____X_,
  XX____X_,
  XX______,
  XXXXX___,
  XX______,
  XX____X_,
  XX____X_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00AB[ 32] = { /* code 00AB */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X___X,________,
  __XX__XX,________,
  _XX__XX_,________,
  _XX__XX_,________,
  __XX__XX,________,
  ___X___X,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00AC[ 32] = { /* code 00AC */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00AD[ 16] = { /* code 00AD */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00AE[ 32] = { /* code 00AE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __X_____,X_______,
  _X______,_X______,
  X__XXXX_,__X_____,
  X__XX_XX,__X_____,
  X__XXXX_,__X_____,
  X__XX_XX,__X_____,
  X__XX__X,X_X_____,
  _X______,_X______,
  __X_____,X_______,
  ___XXXXX,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00AF[ 16] = { /* code 00AF */
  ________,
  X__XX___,
  X__XX___,
  ________,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00B0[ 16] = { /* code 00B0 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00B1[ 32] = { /* code 00B1 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  __XXXXXX,X_______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  __XXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00B2[ 16] = { /* code 00B2 */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00B3[ 16] = { /* code 00B3 */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00B4[ 16] = { /* code 00B4 */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00B5[ 16] = { /* code 00B5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX__XXX_,
  XXXX_XX_,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00B6[ 16] = { /* code 00B6 */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  XXXXX_X_,
  XXXXX_X_,
  XXXXX_X_,
  XXXXX_X_,
  _XXXX_X_,
  ____X_X_,
  ____X_X_,
  ____X_X_,
  ____X_X_,
  ____X_X_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00B7[ 16] = { /* code 00B7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00B8[ 16] = { /* code 00B8 */
  ________,
  ________,
  ________,
  _XX_XX__,
  _XX_XX__,
  ________,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XXXXXXX_,
  XX______,
  XX____X_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00B9[ 32] = { /* code 00B9 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXX___X_,__XXXX__,
  XXX___X_,_XX__XX_,
  X_XX__X_,_XX__XX_,
  X_XX__X_,_XX__XX_,
  X__XX_X_,_XX__XX_,
  X__XX_X_,__XXXX__,
  X___XXX_,________,
  X___XXX_,__XXXX__,
  X____XX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00BA[ 16] = { /* code 00BA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX___X__,
  XX______,
  XXXXX___,
  XX______,
  XX___X__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00BB[ 32] = { /* code 00BB */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X___X__,________,
  _XX__XX_,________,
  __XX__XX,________,
  __XX__XX,________,
  _XX__XX_,________,
  _X___X__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00BC[ 16] = { /* code 00BC */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00BD[ 16] = { /* code 00BD */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX____X_,
  XX____X_,
  XX______,
  _XXXXX__,
  _____XX_,
  X____XX_,
  X____XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00BE[ 16] = { /* code 00BE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX___X__,
  XXX_____,
  _XXXX___,
  ___XXX__,
  X___XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00BF[ 16] = { /* code 00BF */
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00C0[ 32] = { /* code 00C0 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  __XX_XX_,________,
  __XX_XX_,________,
  _XX___XX,________,
  _XXXXXXX,________,
  _XX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00C1[ 16] = { /* code 00C1 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  XX______,
  XX______,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00C2[ 16] = { /* code 00C2 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00C3[ 16] = { /* code 00C3 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00C4[ 32] = { /* code 00C4 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  _XX___XX,________,
  _XX___XX,________,
  XXXXXXXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00C5[ 16] = { /* code 00C5 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00C6[ 32] = { /* code 00C6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX___XX_,__XX____,
  _XX__XX_,_XX_____,
  __XX_XX_,XX______,
  __XX_XX_,XX______,
  __XXXXXX,XX______,
  __XX_XX_,XX______,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  XX___XX_,__XX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00C7[ 16] = { /* code 00C7 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  X____XX_,
  X____XX_,
  _____XX_,
  __XXXX__,
  _____XX_,
  X____XX_,
  X____XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00C8[ 16] = { /* code 00C8 */
  ________,
  ________,
  ________,
  ________,
  X_____X_,
  X____XX_,
  X___XXX_,
  X__XXXX_,
  X_XXX_X_,
  XXXX__X_,
  XXX___X_,
  XX____X_,
  X_____X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00C9[ 16] = { /* code 00C9 */
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  X_____X_,
  X____XX_,
  X___XXX_,
  X__XXXX_,
  X_XXX_X_,
  XXXX__X_,
  XXX___X_,
  XX____X_,
  X_____X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00CA[ 16] = { /* code 00CA */
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX__XX__,
  XX__XX__,
  XX_XX___,
  XXXX____,
  XX_XX___,
  XX__XX__,
  XX__XX__,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00CB[ 32] = { /* code 00CB */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  _XX____X,X_______,
  XX_____X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00CC[ 32] = { /* code 00CC */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXX____X,XX______,
  XXX____X,XX______,
  X_XX__X_,XX______,
  X_XX__X_,XX______,
  X__XXX__,XX______,
  X__XXX__,XX______,
  X___X___,XX______,
  X___X___,XX______,
  X_______,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00CD[ 32] = { /* code 00CD */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XXXXXXXX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00CE[ 32] = { /* code 00CE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XXXXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00CF[ 32] = { /* code 00CF */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00D0[ 16] = { /* code 00D0 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00D1[ 16] = { /* code 00D1 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX____X_,
  XX____X_,
  XX______,
  XX______,
  XX______,
  XX____X_,
  XX____X_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00D2[ 16] = { /* code 00D2 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00D3[ 32] = { /* code 00D3 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  _XX__XX_,________,
  __XXXX__,________,
  ___XXX__,________,
  ___XX___,________,
  ___XX___,________,
  _XXX____,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00D4[ 32] = { /* code 00D4 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  _XXXXXXX,X_______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  _XXXXXXX,X_______,
  ____XX__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00D5[ 32] = { /* code 00D5 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  __XXXX__,________,
  ___XX___,________,
  __XXXX__,________,
  _XX__XX_,________,
  XX____XX,________,
  XX____XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00D6[ 32] = { /* code 00D6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XXXXXXXX,X_______,
  _______X,X_______,
  _______X,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00D7[ 32] = { /* code 00D7 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XXXXXXX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00D8[ 32] = { /* code 00D8 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XXXXXXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00D9[ 32] = { /* code 00D9 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XXXXXXXX,XXXXX___,
  ________,___XX___,
  ________,___XX___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00DA[ 32] = { /* code 00DA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXX____,________,
  __XX____,________,
  __XX____,________,
  __XXXXXX,________,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XXXXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00DB[ 32] = { /* code 00DB */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXXXXX__,XX______,
  XX___XX_,XX______,
  XX___XX_,XX______,
  XX___XX_,XX______,
  XX___XX_,XX______,
  XXXXXX__,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00DC[ 16] = { /* code 00DC */
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00DD[ 16] = { /* code 00DD */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  X____XX_,
  X____XX_,
  _____XX_,
  __XXXXX_,
  _____XX_,
  X____XX_,
  X____XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00DE[ 32] = { /* code 00DE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX____XX,XXXX____,
  XX___XX_,___XX___,
  XX___XX_,___XX___,
  XX___XX_,___XX___,
  XXXXXXX_,___XX___,
  XX___XX_,___XX___,
  XX___XX_,___XX___,
  XX___XX_,___XX___,
  XX____XX,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00DF[ 32] = { /* code 00DF */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  __XXXXXX,________,
  ___XX_XX,________,
  __XX__XX,________,
  _XX___XX,________,
  XX____XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00E0[ 16] = { /* code 00E0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  _____XX_,
  _XXXXXX_,
  XX___XX_,
  XX___XX_,
  _XXXXXX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00E1[ 16] = { /* code 00E1 */
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX_____,
  XX______,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00E2[ 16] = { /* code 00E2 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00E3[ 16] = { /* code 00E3 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00E4[ 32] = { /* code 00E4 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  _XX__XX_,________,
  _XX__XX_,________,
  XXXXXXXX,________,
  XX____XX,________,
  XX____XX,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00E5[ 16] = { /* code 00E5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XXXXXXX_,
  XX______,
  XX____X_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00E6[ 32] = { /* code 00E6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX___XX_,__XX____,
  _XX__XX_,_XX_____,
  __XX_XX_,XX______,
  ___XXXXX,X_______,
  __XX_XX_,XX______,
  _XX__XX_,_XX_____,
  XX___XX_,__XX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00E7[ 16] = { /* code 00E7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  X___XX__,
  ____XX__,
  _XXXX___,
  ____XX__,
  X___XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00E8[ 16] = { /* code 00E8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X____X__,
  X___XX__,
  X__XXX__,
  X_XX_X__,
  XXX__X__,
  XX___X__,
  X____X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00E9[ 16] = { /* code 00E9 */
  ________,
  ________,
  ________,
  _X___X__,
  __XXX___,
  ________,
  X____X__,
  X___XX__,
  X__XXX__,
  X_XX_X__,
  XXX__X__,
  XX___X__,
  X____X__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00EA[ 16] = { /* code 00EA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX__XX__,
  XX__XX__,
  XXXXX___,
  XX__XX__,
  XX__XX__,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00EB[ 32] = { /* code 00EB */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  _XX___XX,________,
  XX____XX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00EC[ 32] = { /* code 00EC */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX_____X,X_______,
  XXX___XX,X_______,
  XXXX_XXX,X_______,
  XX_XXX_X,X_______,
  XX_XXX_X,X_______,
  XX__X__X,X_______,
  XX_____X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00ED[ 16] = { /* code 00ED */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00EE[ 16] = { /* code 00EE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00EF[ 16] = { /* code 00EF */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00F0[ 16] = { /* code 00F0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XXX__,
  XXX__XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00F1[ 16] = { /* code 00F1 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX___X__,
  XX______,
  XX______,
  XX______,
  XX___X__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00F2[ 16] = { /* code 00F2 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00F3[ 16] = { /* code 00F3 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  __XXX___,
  ___XX___,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00F4[ 32] = { /* code 00F4 */
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  _XXXXXXX,X_______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  _XXXXXXX,X_______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00F5[ 16] = { /* code 00F5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  __XX____,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00F6[ 32] = { /* code 00F6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX___XX_,________,
  XX___XX_,________,
  XX___XX_,________,
  XX___XX_,________,
  XX___XX_,________,
  XX___XX_,________,
  XXXXXXXX,________,
  ______XX,________,
  ______XX,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00F7[ 16] = { /* code 00F7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXXX_,
  _____XX_,
  _____XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00F8[ 32] = { /* code 00F8 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XXXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00F9[ 32] = { /* code 00F9 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XXXXXXXX,XXX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00FA[ 32] = { /* code 00FA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXX___,________,
  ___XX___,________,
  ___XXXXX,________,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00FB[ 32] = { /* code 00FB */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX______,XX______,
  XX______,XX______,
  XXXXX___,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XXXXX___,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00FC[ 16] = { /* code 00FC */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XXXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XXXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00FD[ 16] = { /* code 00FD */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  X___XX__,
  ____XX__,
  _XXXXX__,
  ____XX__,
  X___XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00FE[ 32] = { /* code 00FE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX___XXX,XX______,
  XX__XX__,_XX_____,
  XX__XX__,_XX_____,
  XXXXXX__,_XX_____,
  XX__XX__,_XX_____,
  XX__XX__,_XX_____,
  XX___XXX,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTahoma16b_00FF[ 16] = { /* code 00FF */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXXX_,
  _XX__XX_,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontTahoma16b_CharInfo[192] = {
   {   4,   4,  1, acGUI_FontTahoma16b_0020 } /* code 0020 */
  ,{   5,   5,  1, acGUI_FontTahoma16b_0021 } /* code 0021 */
  ,{   6,   6,  1, acGUI_FontTahoma16b_0022 } /* code 0022 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_0023 } /* code 0023 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0024 } /* code 0024 */
  ,{  14,  14,  2, acGUI_FontTahoma16b_0025 } /* code 0025 */
  ,{  11,  11,  2, acGUI_FontTahoma16b_0026 } /* code 0026 */
  ,{   4,   4,  1, acGUI_FontTahoma16b_0027 } /* code 0027 */
  ,{   6,   6,  1, acGUI_FontTahoma16b_0028 } /* code 0028 */
  ,{   6,   6,  1, acGUI_FontTahoma16b_0029 } /* code 0029 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_002A } /* code 002A */
  ,{  11,  11,  2, acGUI_FontTahoma16b_002B } /* code 002B */
  ,{   4,   4,  1, acGUI_FontTahoma16b_002C } /* code 002C */
  ,{   6,   6,  1, acGUI_FontTahoma16b_002D } /* code 002D */
  ,{   4,   4,  1, acGUI_FontTahoma16b_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_FontTahoma16b_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0039 } /* code 0039 */
  ,{   5,   5,  1, acGUI_FontTahoma16b_003A } /* code 003A */
  ,{   5,   5,  1, acGUI_FontTahoma16b_003B } /* code 003B */
  ,{  11,  11,  2, acGUI_FontTahoma16b_003C } /* code 003C */
  ,{  11,  11,  2, acGUI_FontTahoma16b_003D } /* code 003D */
  ,{  11,  11,  2, acGUI_FontTahoma16b_003E } /* code 003E */
  ,{   7,   7,  1, acGUI_FontTahoma16b_003F } /* code 003F */
  ,{  10,  10,  2, acGUI_FontTahoma16b_0040 } /* code 0040 */
  ,{  10,  10,  2, acGUI_FontTahoma16b_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0043 } /* code 0043 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_0044 } /* code 0044 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_0045 } /* code 0045 */
  ,{   6,   6,  1, acGUI_FontTahoma16b_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0047 } /* code 0047 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_0048 } /* code 0048 */
  ,{   5,   5,  1, acGUI_FontTahoma16b_0049 } /* code 0049 */
  ,{   6,   6,  1, acGUI_FontTahoma16b_004A } /* code 004A */
  ,{   8,   8,  1, acGUI_FontTahoma16b_004B } /* code 004B */
  ,{   7,   7,  1, acGUI_FontTahoma16b_004C } /* code 004C */
  ,{  11,  11,  2, acGUI_FontTahoma16b_004D } /* code 004D */
  ,{   8,   8,  1, acGUI_FontTahoma16b_004E } /* code 004E */
  ,{   9,   9,  2, acGUI_FontTahoma16b_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0050 } /* code 0050 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_0051 } /* code 0051 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_0052 } /* code 0052 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0053 } /* code 0053 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0055 } /* code 0055 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_0056 } /* code 0056 */
  ,{  13,  13,  2, acGUI_FontTahoma16b_0057 } /* code 0057 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_0058 } /* code 0058 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_0059 } /* code 0059 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_005A } /* code 005A */
  ,{   6,   6,  1, acGUI_FontTahoma16b_005B } /* code 005B */
  ,{   8,   8,  1, acGUI_FontTahoma16b_005C } /* code 005C */
  ,{   6,   6,  1, acGUI_FontTahoma16b_005D } /* code 005D */
  ,{  11,  11,  2, acGUI_FontTahoma16b_005E } /* code 005E */
  ,{   8,   8,  1, acGUI_FontTahoma16b_005F } /* code 005F */
  ,{   7,   7,  1, acGUI_FontTahoma16b_0060 } /* code 0060 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0062 } /* code 0062 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_0063 } /* code 0063 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0064 } /* code 0064 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0065 } /* code 0065 */
  ,{   5,   5,  1, acGUI_FontTahoma16b_0066 } /* code 0066 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0068 } /* code 0068 */
  ,{   3,   3,  1, acGUI_FontTahoma16b_0069 } /* code 0069 */
  ,{   4,   4,  1, acGUI_FontTahoma16b_006A } /* code 006A */
  ,{   7,   7,  1, acGUI_FontTahoma16b_006B } /* code 006B */
  ,{   3,   3,  1, acGUI_FontTahoma16b_006C } /* code 006C */
  ,{  11,  11,  2, acGUI_FontTahoma16b_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_FontTahoma16b_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_FontTahoma16b_006F } /* code 006F */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0071 } /* code 0071 */
  ,{   6,   6,  1, acGUI_FontTahoma16b_0072 } /* code 0072 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_0073 } /* code 0073 */
  ,{   6,   6,  1, acGUI_FontTahoma16b_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0075 } /* code 0075 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0076 } /* code 0076 */
  ,{  11,  11,  2, acGUI_FontTahoma16b_0077 } /* code 0077 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_0078 } /* code 0078 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_0079 } /* code 0079 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_007A } /* code 007A */
  ,{   7,   7,  1, acGUI_FontTahoma16b_007B } /* code 007B */
  ,{   7,   7,  1, acGUI_FontTahoma16b_007C } /* code 007C */
  ,{   7,   7,  1, acGUI_FontTahoma16b_007D } /* code 007D */
  ,{  11,  11,  2, acGUI_FontTahoma16b_007E } /* code 007E */
  ,{   9,   9,  2, acGUI_FontTahoma16b_007F } /* code 007F */
  ,{   4,   4,  1, acGUI_FontTahoma16b_00A0 } /* code 00A0 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00A1 } /* code 00A1 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00A2 } /* code 00A2 */
  ,{   6,   6,  1, acGUI_FontTahoma16b_00A3 } /* code 00A3 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00A4 } /* code 00A4 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00A5 } /* code 00A5 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00A6 } /* code 00A6 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00A7 } /* code 00A7 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00A8 } /* code 00A8 */
  ,{  12,  12,  2, acGUI_FontTahoma16b_00A9 } /* code 00A9 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00AA } /* code 00AA */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00AB } /* code 00AB */
  ,{  11,  11,  2, acGUI_FontTahoma16b_00AC } /* code 00AC */
  ,{   6,   6,  1, acGUI_FontTahoma16b_00AD } /* code 00AD */
  ,{  12,  12,  2, acGUI_FontTahoma16b_00AE } /* code 00AE */
  ,{   5,   5,  1, acGUI_FontTahoma16b_00AF } /* code 00AF */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00B0 } /* code 00B0 */
  ,{  11,  11,  2, acGUI_FontTahoma16b_00B1 } /* code 00B1 */
  ,{   5,   5,  1, acGUI_FontTahoma16b_00B2 } /* code 00B2 */
  ,{   3,   3,  1, acGUI_FontTahoma16b_00B3 } /* code 00B3 */
  ,{   6,   6,  1, acGUI_FontTahoma16b_00B4 } /* code 00B4 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00B5 } /* code 00B5 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00B6 } /* code 00B6 */
  ,{   5,   5,  1, acGUI_FontTahoma16b_00B7 } /* code 00B7 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00B8 } /* code 00B8 */
  ,{  16,  16,  2, acGUI_FontTahoma16b_00B9 } /* code 00B9 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00BA } /* code 00BA */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00BB } /* code 00BB */
  ,{   4,   4,  1, acGUI_FontTahoma16b_00BC } /* code 00BC */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00BD } /* code 00BD */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00BE } /* code 00BE */
  ,{   3,   3,  1, acGUI_FontTahoma16b_00BF } /* code 00BF */
  ,{  10,  10,  2, acGUI_FontTahoma16b_00C0 } /* code 00C0 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00C1 } /* code 00C1 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00C2 } /* code 00C2 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00C3 } /* code 00C3 */
  ,{  10,  10,  2, acGUI_FontTahoma16b_00C4 } /* code 00C4 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00C5 } /* code 00C5 */
  ,{  13,  13,  2, acGUI_FontTahoma16b_00C6 } /* code 00C6 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00C7 } /* code 00C7 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00C8 } /* code 00C8 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00C9 } /* code 00C9 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00CA } /* code 00CA */
  ,{  10,  10,  2, acGUI_FontTahoma16b_00CB } /* code 00CB */
  ,{  11,  11,  2, acGUI_FontTahoma16b_00CC } /* code 00CC */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00CD } /* code 00CD */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00CE } /* code 00CE */
  ,{  10,  10,  2, acGUI_FontTahoma16b_00CF } /* code 00CF */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00D0 } /* code 00D0 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00D1 } /* code 00D1 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00D2 } /* code 00D2 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00D3 } /* code 00D3 */
  ,{  11,  11,  2, acGUI_FontTahoma16b_00D4 } /* code 00D4 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00D5 } /* code 00D5 */
  ,{  10,  10,  2, acGUI_FontTahoma16b_00D6 } /* code 00D6 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00D7 } /* code 00D7 */
  ,{  13,  13,  2, acGUI_FontTahoma16b_00D8 } /* code 00D8 */
  ,{  14,  14,  2, acGUI_FontTahoma16b_00D9 } /* code 00D9 */
  ,{  10,  10,  2, acGUI_FontTahoma16b_00DA } /* code 00DA */
  ,{  11,  11,  2, acGUI_FontTahoma16b_00DB } /* code 00DB */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00DC } /* code 00DC */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00DD } /* code 00DD */
  ,{  14,  14,  2, acGUI_FontTahoma16b_00DE } /* code 00DE */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00DF } /* code 00DF */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00E0 } /* code 00E0 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00E1 } /* code 00E1 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00E2 } /* code 00E2 */
  ,{   6,   6,  1, acGUI_FontTahoma16b_00E3 } /* code 00E3 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00E4 } /* code 00E4 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00E5 } /* code 00E5 */
  ,{  13,  13,  2, acGUI_FontTahoma16b_00E6 } /* code 00E6 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00E7 } /* code 00E7 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00E8 } /* code 00E8 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00E9 } /* code 00E9 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00EA } /* code 00EA */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00EB } /* code 00EB */
  ,{  10,  10,  2, acGUI_FontTahoma16b_00EC } /* code 00EC */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00ED } /* code 00ED */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00EE } /* code 00EE */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00EF } /* code 00EF */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00F0 } /* code 00F0 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00F1 } /* code 00F1 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00F2 } /* code 00F2 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00F3 } /* code 00F3 */
  ,{  11,  11,  2, acGUI_FontTahoma16b_00F4 } /* code 00F4 */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00F5 } /* code 00F5 */
  ,{   9,   9,  2, acGUI_FontTahoma16b_00F6 } /* code 00F6 */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00F7 } /* code 00F7 */
  ,{  11,  11,  2, acGUI_FontTahoma16b_00F8 } /* code 00F8 */
  ,{  12,  12,  2, acGUI_FontTahoma16b_00F9 } /* code 00F9 */
  ,{  10,  10,  2, acGUI_FontTahoma16b_00FA } /* code 00FA */
  ,{  11,  11,  2, acGUI_FontTahoma16b_00FB } /* code 00FB */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00FC } /* code 00FC */
  ,{   7,   7,  1, acGUI_FontTahoma16b_00FD } /* code 00FD */
  ,{  12,  12,  2, acGUI_FontTahoma16b_00FE } /* code 00FE */
  ,{   8,   8,  1, acGUI_FontTahoma16b_00FF } /* code 00FF */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTahoma16b_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontTahoma16b_CharInfo[ 96] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTahoma16b_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontTahoma16b_CharInfo[  0] /* address of first character */
  ,&GUI_FontTahoma16b_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontTahoma16b = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontTahoma16b_Prop1}
  ,13 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,9 /* Height of capital characters */
};

